import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const pkgPath = path.join(__dirname, '..', 'package.json');

try {
  let pkg;
  let version = "0.1.0";
  try {
    pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8'));
    version = pkg.version || "0.1.0";
  } catch (e) {
    console.error("Warning: could not read package.json version.");
  }

  let commitSha = "unknown";
  try {
    commitSha = execSync('git rev-parse --short HEAD', { stdio: 'pipe' }).toString().trim();
  } catch (e) {
    // Ignore error
  }

  let buildNumber = "unknown";
  try {
    buildNumber = execSync('git rev-list --count HEAD', { stdio: 'pipe' }).toString().trim();
  } catch (e) {
    // Ignore error
  }

  const buildDate = new Date().toISOString();

  const content = `// This file is auto-generated by scripts/generate-version.mjs
// Do not edit manually

export const APP_VERSION = "${version}";
export const APP_VERSION_LABEL = "v${version}";
export const APP_COMMIT_SHA = "${commitSha}";
export const APP_BUILD_NUMBER = "${buildNumber}";
export const APP_BUILD_DATE = "${buildDate}";
`;

  const destPath = path.join(__dirname, '..', 'src', 'version.ts');
  fs.writeFileSync(destPath, content, 'utf-8');
  console.log(`Version generated: v${version} (build ${buildNumber}, commit ${commitSha})`);
} catch (e) {
  console.error("Error generating version file:", e.message);
}
