// This file is auto-generated by scripts/generate-version.mjs
// Do not edit manually

export const APP_VERSION = "0.27.1";
export const APP_VERSION_LABEL = "v0.27.1";
export const APP_COMMIT_SHA = "5518fca";
export const APP_BUILD_NUMBER = "84";
export const APP_BUILD_DATE = "2026-06-13T16:21:57.103Z";
export const APP_BUILD_SOURCE: string = "local";
