// This file is auto-generated by scripts/generate-version.mjs
// Do not edit manually

export const APP_VERSION = "0.30.6";
export const APP_VERSION_LABEL = "v0.30.6";
export const APP_COMMIT_SHA = "104ef27";
export const APP_BUILD_NUMBER = "105";
export const APP_BUILD_DATE = "2026-06-14T04:03:52.645Z";
export const APP_BUILD_SOURCE: string = "local";
