// This file is auto-generated by scripts/generate-version.mjs
// Do not edit manually

export const APP_VERSION = "0.26.0";
export const APP_VERSION_LABEL = "v0.26.0";
export const APP_COMMIT_SHA = "fab4aa2";
export const APP_BUILD_NUMBER = "80";
export const APP_BUILD_DATE = "2026-06-13T15:49:59.632Z";
export const APP_BUILD_SOURCE: string = "local";
